Add: First program
Dev-Soumyaranjan/Java-Coding-Questions pull request #5
Opened 2022-07-23 06:57 UTC by Sudarsan-Pradhan

I added a java program which will check an entered number given by the user is a palindrome number or not

2022-07-23 07:19 UTC, Dev-Soumyaranjan requested changes
Please do the following changes:
1.Change "string" to number at line number 8
2. Remove the comment line 28 and merge it to the line number 27 and make it single comment line.
3. Do the same thing with line number 52 and 53

2022-07-23 08:08 UTC, Dev-Soumyaranjan commented on PrepInsta Top 100 Codes/Getting Started/Check_Palindrome.java
> +* To do so, we’ll first reverse the string input using loops and check if it matches the original number.
Change "string" to number at line number 8

2022-07-23 08:10 UTC, Dev-Soumyaranjan commented on PrepInsta Top 100 Codes/Getting Started/Check_Palindrome.java
> +        // returns false then it is not
Remove the comment line 28 and merge it to the line number 27 and make it single comment line.

2022-07-23 08:10 UTC, Dev-Soumyaranjan commented on PrepInsta Top 100 Codes/Getting Started/Check_Palindrome.java
> +        // number will store in rev
Remove the comment line 53 and merge it to the line number 52 and make it single comment line.

2022-07-23 08:21 UTC, Dev-Soumyaranjan commented
@all-contributors please add @Sudarsan-Pradhan  for adding new code

2022-07-23 18:46 UTC, Dev-Soumyaranjan commented
@all-contributors please add @Sudarsan-Pradhan for code

2022-07-23 18:46 UTC, Dev-Soumyaranjan commented
@all-contributors please add @Sudarsan-Pradhan for code

2022-07-24 05:46 UTC, Sudarsan-Pradhan commented
i have changed the code accordingly. just check it out

2022-07-24 05:48 UTC, Dev-Soumyaranjan approved these changes
Sounds good✨Thanks for contributing. I am going to merge it

2022-07-24 05:49 UTC, Sudarsan-Pradhan commented
Thank you very much

2022-07-24 05:50 UTC, merged

2022-07-24 11:43 UTC, Dev-Soumyaranjan commented
https://github.com/all-contributors please add @Sudarsan-Pradhan for code

2022-07-24 11:44 UTC, Dev-Soumyaranjan commented
@all-contributors please add @Sudarsan-Pradhan for code